sudo: required

services:
  - docker 


before_install:
  - docker build -t duyguemre/docker-react -f ./server/Dockerfile.dev ./server


script:
  - docker run duyguemre/docker-react npm run test -- --coverage &