sudo: required

services:
  - docker


before_install:
  - docker build -t duyguemre/multi-server -f ./server/Dockerfile ./server
 
scripts:
   - docker run duyguemre/multi-server npm run test -- --coverage &
