sudo: required

services:
  - docker

before_install:
  - docker build -t duyguemre/multiserver -f ./server/Dockerfile ./server

scripts:
  - docker run duyguemre/multiserver npm run test -- --coverage