sudo: required

services:
  - docker

before_install:
  - docker build -t duyguemre/react-test -f ./client/Dockerfile.dev ./client


scripts:
  - docker run duyguemre/react-test npm test -- --converage &

after_success:
  - docker build -t duyguemre/multi-client -f ./client/Dockerfile ./client
  - docker build -t duyguemre/multi-server -f ./client/Dockerfile ./server
  - docker build -t duyguemre/multi-nginx -f ./client/Dockerfile ./nginx
  - docker build -t duyguemre/multi-worker -f ./client/Dockerfile ./worker

