sudo: required

services:
  - docker


before_install:
  - docker build -t duyguemre/multi-client -f ./client/Dockerfile ./client
 
scripts:
   - docker run duyguemre/multi-client npm run test -- --coverage &
